Jdp210901 30
piotr-grosicki/project-jdp-2109-01 pull request #12
Opened 2021-09-27 12:32 UTC by JanuszSt-JavaProjects

2021-09-27 13:01 UTC, JanuszSt-JavaProjects commented
Piotrze  - skoro nie obsługujemy 'przełączania" flagi "isBlocked" - to po  co nam w ogóle to pole ? 
Może je wywalić ?

2021-09-27 13:08 UTC, piotr-grosicki requested changes
do poprawki zgodnie z rozmowa na czacie

2021-09-27 19:02 UTC, piotr-grosicki requested changes

2021-09-27 19:02 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/SecurityService.java
> +    public LocalDateTime setExpirationTime() {
raczej get ;)

2021-09-27 19:03 UTC, piotr-grosicki requested changes

2021-09-27 19:03 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/SecurityService.java
> +public class SecurityService {
swoja droga czemu dwie metody? nie lepsza by byla jedna, ktora dla danego usera generuje nowy klucz, zapisuje go jako encje w bazie, i przypisuje go userowi?

2021-09-27 19:34 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/SecurityService.java
> +public class SecurityService {
No - nie upraszczasz ... ;) ))))

2021-09-28 07:53 UTC, JanuszSt-JavaProjects commented
Zauważyłem, że mi się zaplątał sysout 
    @PutMapping(value = "")
    public UserDto update(@RequestBody UserDto userDto){

        String individualUserId =userDto.getIndividualUserId();
        System.out.println(individualUserId);

wywalę go przy kolejnym commicie.

2021-09-28 08:00 UTC, piotr-grosicki requested changes

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public <T> boolean validate(T objectDto) {
w repozytorium nie trzymamy zakomentowanego kodu

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    @PostMapping()
tutaj puste nawiasy

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    @PutMapping(value = "")
a tutaj nawiasy z pustym value. Estetyka kodu jest bardzo wazna :)

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        Key actualisedKey =new Key();
updated troche lepiej brzmi ;)

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private String individualUserId;
co to jest individual user id? to nie jest to samo co id?

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/Key.java
> +        SecurityService service = new SecurityService();
encja nie moze wykonywac jakiejkolwiek logiki, a tym bardziej tworzyc serwis w konstruktorze. To serwis (bean springowy) powinien umiec utworzyc key, przypisac go do usera i zapisac w bazie

2021-09-28 08:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/KeyValidator.java
> +    <T> boolean validate(T objectDto);
jaki jest cel tej klasy? po co tutaj beda validowane dto skoro klucz bedzie dostarczany w request paramsach?

2021-09-28 08:11 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/KeyValidator.java
> +    <T> boolean validate(T objectDto);
to jest "na później" ;) 
OK.

2021-09-28 08:12 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/KeyValidator.java
> +    <T> boolean validate(T objectDto);
ja rozumiem ze jest na pozniej, ale nie ma sensu za bardzo bo zadne dto nie beda nigdy validowane ;)

2021-09-28 08:15 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/Key.java
> +        SecurityService service = new SecurityService();
OK

2021-09-28 10:12 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/KeyValidator.java
> +    <T> boolean validate(T objectDto);
Oj tam.. to był bardzo ...'przelot
ny pomysł ' .. ;)

2021-09-28 13:20 UTC, piotr-grosicki requested changes

2021-09-28 13:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        userDto.setFirstname("");
tak jak wspomnialem kilka razy na czacie, ten update, ktory robisz nie powinien modyfikowac innych pol niz klucz / expiration date

2021-09-28 13:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/Key.java
> +    User user;
to pole powinno byc prywatne

2021-09-28 13:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private GroupDto groupDto;              // remove comment after GroupDto.class implementation //
czemu to zostalo zmienione w tym PR? to nie ma nic wspolnego z obecnym zadaniem

2021-09-28 13:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        userDto.setAccessKey(key.getAccessKey());
to jest powielenie tego co mamy w encji `Key`, potrzebne to jest?

2021-09-28 13:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        userDto.setExpirationTime(key.getExpirationTime());
j.w.

2021-09-28 16:46 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        userDto.setFirstname("");
zrobione

2021-09-28 16:48 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/Key.java
> +    User user;
zrobione

2021-09-28 16:51 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private GroupDto groupDto;              // remove comment after GroupDto.class implementation //
Fakt. testowałem coś na edndpoincie Produktu i było mi potrzebne. Zmieniam.

2021-09-28 16:56 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +    private String firstname;
usunięte

2021-09-28 16:59 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private String firstname;
Wiesz ? Ciężko mi patrzeć i nie widzieć całości. Zawsze robiła cały kod sam. 
Domyślam się, że w pracy w grupie takie podejście jest niezbędne bo jakby każdy sobie zrobił całą własną encję z kilkoma polami to potem byśmy się zaje... chali z uzgadnianiem commitów.

2021-09-28 17:24 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        userDto.setAccessKey(key.getAccessKey());
usunięte

2021-09-28 17:24 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        userDto.setExpirationTime(key.getExpirationTime());
j.w ;)

2021-09-28 18:00 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        Key newKey = securityService.generateKey();
OK. Ale - jeśli mogę -to ciut później. OK ? ;)

2021-09-28 18:01 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    User findByKey_AccessKey(String accessKey);
usunięte

2021-09-28 18:01 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +    public User findByKey(String accessKey) {
usuniete

2021-09-28 18:12 UTC, JanuszSt-JavaProjects commented
Nie mam pojęcia jak rozwiązać ten konflikt, bo w IntelliJ nie widzę żadnego konfliktu ....
Nie robiłem żadnego 'amenda' czy 'force-a'

2021-09-29 10:38 UTC, closed without merging