ProductController added
piotr-grosicki/project-jdp-2109-01 pull request #2
Opened 2021-09-24 20:37 UTC by JanuszSt-JavaProjects

2021-09-24 20:51 UTC, piotr-grosicki requested changes
brakuje klas dto pozwalajacych nam przetestowac te endpointy

2021-09-24 21:02 UTC, JanuszSt-JavaProjects commented
Przetestowałem Postmanem.

2021-09-24 21:03 UTC, JanuszSt-JavaProjects commented
Prze

2021-09-24 21:08 UTC, JanuszSt-JavaProjects commented
Sorry  - nie wiem dlaczego  się zamknął ten request.

2021-09-25 09:46 UTC, piotr-grosicki requested changes

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/products")
teraz wyszlo `/product/products`

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/products")
`/products` powinno byc w sciezce na gorze klasy

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @PostMapping(value = "/", consumes = MediaType.APPLICATION_JSON_VALUE)
value powinno byc puste

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public String addProduct(@RequestBody ProductDto newProduct) {
ta metoda powinna zwracac `ProductDto`

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public String updateProduct(@PathVariable ("id") Long productId, @RequestBody ProductDto productDto) {
ta metoda powinna zwracac `ProductDto`

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public String removeProduct(@PathVariable ("id") Long productId) {
ta metode nie powinna nic zwracac

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +public class Product {
ta klasa nie powinna powstac w tym PR, tylko dto

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +//    private Group group;              // remove comment after Group.class implementation
tutaj powinno byc `GroupDto` a nie `Group`

2021-09-25 09:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +@CrossOrigin(origins = "*")
crossorigin nie jest potrzebny w tym projekcie, odzywamy sie do endpointow tylko przez postmana

2021-09-25 16:24 UTC, piotr-grosicki requested changes

2021-09-25 16:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/{id}")
Czemu tutaj jest inaczej niz w tych nizej? Moze lepiej bylo by uzyc '@GetMapping'?

2021-09-25 16:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET)
To samo co wyzej :)

2021-09-25 16:39 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET)
Bo ćwiczę różne adnotacje :). Dlatego dla obu GET-ów  zastosowałem inny zapis.

2021-09-25 17:17 UTC, piotr-grosicki approved these changes

2021-09-25 17:17 UTC, merged