Jdp210901 20
piotr-grosicki/project-jdp-2109-01 pull request #31
Opened 2021-10-02 22:55 UTC by lukgrz

2021-10-03 09:11 UTC, leszczu89 requested changes

2021-10-03 09:11 UTC, leszczu89 commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +    public void TestDeleteUser() {
Metody piszemy z małej litery

2021-10-03 09:11 UTC, leszczu89 commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +    public void TestSaveUserWithCart() {
j.w.

2021-10-03 09:11 UTC, leszczu89 commented on src/test/java/com/kodilla/ecommercee/repository/UserRepositoryTestSuite.java
> +    public void TestDeleteUserWithCart() {
j.w.

2021-10-03 13:33 UTC, AleksanderKolompar reviewed
Commit zawiera zmiany które zostały już dodane do głownego brancha. Rebase/merge przed commitem.

2021-10-04 16:24 UTC, leszczu89 commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +    @After
Zgodnie z sugestią PM wystarczy tylko @After

2021-10-04 17:01 UTC, lukgrz commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +    @After
Poprawione wasze sugestie, troche wtopa z tymi nazwami metod :D

2021-10-04 17:15 UTC, leszczu89 approved these changes

2021-10-04 17:15 UTC, leszczu89 commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +    @After
Nie bój nic ;) Każdy z nas ma jakieś wtopy ;) W końcu uczymy się ;)

2021-10-07 12:22 UTC, AleksanderKolompar commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +        System.out.println("test 1");
SOUT są zbędne w testach

2021-10-07 16:38 UTC, JanuszSt-JavaProjects commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +        System.out.println("test 1");
Ja też wrzucam souty w program, żeby wiedzieć co się dzieje ale fakt: w kodzie produkcyjnym nie powinny się znajdować.

2021-10-09 12:39 UTC, leszczu89 approved these changes

2021-10-09 18:21 UTC, AleksanderKolompar approved these changes

2021-10-10 08:10 UTC, merged