Jdp210901 19
piotr-grosicki/project-jdp-2109-01 pull request #33
Opened 2021-10-03 14:01 UTC by gtrofimiec

2021-10-03 22:29 UTC, AleksanderKolompar requested changes

2021-10-03 22:29 UTC, AleksanderKolompar commented on src/test/java/com/kodilla/ecommercee/repository/CartRepositoryTestSuite.java
> +        assertEquals(1, availableProduct);
Usunięcie koszyka nie powinno usuwać produktu (ktoś inny może chcieć go kupić) -> expected: 2

2021-10-03 22:29 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
>      @ManyToMany(cascade = CascadeType.ALL, mappedBy = "cartList")
Do przemyślenia: czy cokolwiek powinno kaskadować

2021-10-04 16:56 UTC, lukgrz commented on src/test/java/com/kodilla/ecommercee/repository/CartRepositoryTestSuite.java
> +        user.setCart(cart2);
W relacji miedzy user a cart mamny OneToOne wiec nie możemy przypisać 2 cart do 1 usera

2021-10-04 16:56 UTC, lukgrz commented on src/test/java/com/kodilla/ecommercee/repository/CartRepositoryTestSuite.java
> +        product2.getCartList().add(cart);
Wydaje mi się że skoro przypisaliśmy już produkt do koszyka to nie musimy już przypisywać koszyka do produktu. W końcu mamy opisane ralcję między nimi więc powinno sie to dziać z automatu.

2021-10-04 16:56 UTC, lukgrz commented on src/test/java/com/kodilla/ecommercee/repository/CartRepositoryTestSuite.java
> +        }
Try catch zbędne jeżeli nie uda się usunąć karty, po prostu nie przejdzie testu. A w przypadku podania błędnego cartID to program musi sobie poradzić z wyjątkiem, nie test.

2021-10-05 12:30 UTC, closed without merging