Group: full implementation (JDP210901-22)
piotr-grosicki/project-jdp-2109-01 pull request #41
Opened 2021-10-07 12:04 UTC by gtrofimiec

2021-10-07 12:17 UTC, gtrofimiec commented
Teraz powinno być dobrze

2021-10-07 19:13 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +}
Nie masz "deleteGroup". Celowo ?

2021-10-07 22:39 UTC, AleksanderKolompar requested changes

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        return groupMapper.mapGroupToGroupDto(groupService.saveGroup(group));
Wydaje mi się, że w tej linijce dzieje się za dużo. Proponuję rozdzielenie na zapis i zwrócenie przemapowanej group.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.getGroup(groupId);
Obecnie nic nie robi.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public Group(String name, List<Product> productList) {
Ten konstruktor (chyba) nie jest potrzebny.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.findById(groupId);
Rzuci wyjątkiem jeśli nie znajdzie grupy o podanym Id

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        ProductMapper productMapper = new ProductMapper();
ProductMapper niepotrzebny.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                productMapper.mapToProductDtoList(group.getProductList()));
GroupDto powinno zawierać *id* oraz *name*.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        ProductMapper productMapper = new ProductMapper();
Tutaj też nie jest potrzebny.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                productMapper.mapToProductList(groupDto.getProductDtoList()));
Tworzy *Group* tylko z argumentem name. Konstruktor masz już w kodzie.

2021-10-07 22:39 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +}
Po poprawieniu GroupMappera cały ProductMapper możesz usunąć.

2021-10-08 05:40 UTC, gtrofimiec commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +}
No właśnie nie ma jej w specyfikacji. Choć nawet do testów fajnie gdyby zaimplementować ...

2021-10-08 05:41 UTC, gtrofimiec commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        return groupMapper.mapGroupToGroupDto(groupService.getGroup(groupId).get());
Mam już w kodzie wyjątek dla get

2021-10-11 08:02 UTC, leszczu89 approved these changes

2021-10-11 10:48 UTC, leszczu89 requested changes

2021-10-11 10:48 UTC, leszczu89 commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.save(group);
No i gdzie to wyrzucanie wyjątku? ;)

2021-10-11 11:41 UTC, leszczu89 requested changes

2021-10-11 11:41 UTC, leszczu89 commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.save(group);
No ale nadal nie sprawdzasz czy juz istnieje group o takim id

2021-10-11 12:21 UTC, gtrofimiec commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.save(group);
Ale teraz zastanawiam się nad sensem sprawdzania tego id. Skoro jest ono nadawane odgórnie, to czy jest możliwość by nadał drugi raz takie samo skoro są unikalne?

2021-10-12 12:34 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +
Skoro obsługujesz wyjątek, to klauzula 'throws' chyba jest zbędna ? 
(Pytam tylko informacyjnie :) )

2021-10-12 14:10 UTC, JanuszSt-JavaProjects commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +
Uhm. Też ją pamiętam. Byłem przeciw ;) ))))
Tam "throws"  siedział na kontrolerze,  a wyjątek rzucała metoda z dbService, którą ten kontrole wywoływał (że tak uproszczę), więc jakoś tam mogłoby to mieć uzasadnienie. (choć ja bym tego nie zapisał ;) ) Natomiast zapisywanie tego przy metodzie obsługującej ....? Nie jestem przekonany. 
(Ale wtedy też nie byłem ;) ))) ) Dlatego dałem aprove'a i jedyne co to pozwoliłem sobie skomentować ;)

2021-10-12 14:11 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +
to jest jak najbardziej dobra praktyka i polecam stosowanie jej.

2021-10-12 15:58 UTC, lukgrz commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        updatedGroup = groupService.saveGroup(updatedGroup);
Wydaje mi się że używając groupService.saveGroup w metodzie updateGroup będzie ci wywalać GroupAlreadyExistException jeżeli wstawisz Id takie jakie już istnieje, albo będzie tworzyć nową groupe z nowym Id zamiast aktualizować istniejącej.

I wyjątku GroupNotFoundException też ci chyba nigdy nie wyrzuci, bo w tej metodzie nie pobierasz nigdzie grupy

2021-10-12 16:09 UTC, lukgrz requested changes

2021-10-12 16:09 UTC, lukgrz commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        updatedGroup = groupService.saveGroup(updatedGroup);
Wydaje mi się że używając groupService.saveGroup w metodzie updateGroup będzie ci wywalać GroupAlreadyExistException jeżeli wstawisz Id takie jakie już istnieje, albo będzie tworzyć nową groupe z nowym Id zamiast aktualizować istniejącej.

I wyjątku GroupNotFoundException też ci chyba nigdy nie wyrzuci, bo w tej metodzie nie pobierasz nigdzie grupy

2021-10-13 06:30 UTC, gtrofimiec commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        updatedGroup = groupService.saveGroup(updatedGroup);
Dzięki za sugestie. Uwzględniłem :) Dodałem metodę update do GroupService z warunkami.

2021-10-13 16:06 UTC, merged