Jdp210901 36 user soft delete
piotr-grosicki/project-jdp-2109-01 pull request #46
Opened 2021-10-11 13:04 UTC by leszczu89

Aby testy zadziałały dodałam adnotacje @DirtiesContext. Z tego co wyczytałam nie jest to optymalne wyjście, znacznie wydłużające testy, ale jest to jedyne rozwiązanie które znalazłam aby testy przeszły.

2021-10-11 13:33 UTC, gtrofimiec commented on src/main/java/com/kodilla/ecommercee/domain/Key.java
> +@SQLDelete(sql = "UPDATE access_keys SET deleted = true WHERE id = ?")
Może to kolejna głupia uwaga, ale wolę zapytać :)
Działa Ci z odwołaniem do takiej nazwy tabeli? Nie powinno być accessKeys zamiast access_keys?

2021-10-11 14:04 UTC, leszczu89 commented on src/main/java/com/kodilla/ecommercee/domain/Key.java
> +@SQLDelete(sql = "UPDATE access_keys SET deleted = true WHERE id = ?")
No właśnie accessKeys nie chciało mi zadziałać. A w bazie danych tworzy mi się właśnie tabela access_keys. Chyba trzeba zmienić nazwę tabeli na access_keys bo taka nomenklatura zdaje się jest prawidłowa.

2021-10-13 13:39 UTC, JanuszSt-JavaProjects submitted a review, later dismissed

2021-10-15 09:36 UTC, AleksanderKolompar requested changes
Mapper nie powinien przerzucać odpowiedzialności na encje.
- mapper tworzy pusty obiekt
- mapper ustawia wartości pobierane z Dto
- mapper zwraca pełny obiekt
Tym sposobem zdejmujemy ciężar pilnowania konstruktora w encji. Całością zajmie się mapper => dodajemy jeden setter i gotowe.

2021-10-15 09:36 UTC, AleksanderKolompar commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @OneToMany(cascade = CascadeType.MERGE, fetch = FetchType.EAGER, mappedBy = "user", targetEntity = Cart.class)
Zmieniły się założenia relacji na ToMany czy zmiane wymusił soft delete? Może jednak powinno zostać ToOne?

2021-10-17 12:47 UTC, closed without merging