Product Controller implementation fixed
piotr-grosicki/project-jdp-2109-01 pull request #49
Opened 2021-10-11 23:40 UTC by AleksanderKolompar

2021-10-12 07:36 UTC, leszczu89 requested changes

2021-10-12 07:36 UTC, leszczu89 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        product.setId(id);
Nie sprawdzasz nigdzie, czy update-owany produkt faktycznie istnieje

2021-10-13 15:24 UTC, leszczu89 submitted a review, later dismissed

2021-10-13 15:26 UTC, Paula5683 submitted a review, later dismissed

2021-10-13 21:46 UTC, lukgrz approved these changes

2021-10-14 06:08 UTC, leszczu89 reviewed
Nie rozumiem za bardzo czemu testy teraz opierają się o serwis. Wszędzie mamy testy na poziomie repozytorium. Można zawsze zrobić dodatkowe testy serwisów dla wszystkich encji.

2021-10-14 07:13 UTC, leszczu89 commented
> > Nie rozumiem za bardzo czemu testy teraz opierają się o serwis. Wszędzie mamy testy na poziomie repozytorium. Można zawsze zrobić dodatkowe testy serwisów dla wszystkich encji.
> 
> Testujemy encje. Przy pisaniu kontrollerów (zmiany w repozytorium) należało zaktualizować testy. Przy okazji ukryłem implementacje repozytorium za serwisem.

Rozumiem że musiałeś poprawić testy. Tylko dla mnie to trochę brak konsekwencji. I w momencie gdy dorzucimy soft delete, będzie konieczna ponowna zmiana testów bo rekordy nie będą już usuwane tylko updatowane. Zerknij jak zrobiłam soft delete dla encji order. Zaraz poprawie implementacje soft delete dla encji user wg wczorajszych wskazówek PM.

2021-10-14 19:18 UTC, merged