Task JDP210901-3 Added CartDto and implementation for CartController
piotr-grosicki/project-jdp-2109-01 pull request #6
Opened 2021-09-25 12:40 UTC by leszczu89

2021-09-25 12:50 UTC, piotr-grosicki requested changes
Jak na moje to sie chyba nie zgrywa troche z Waszym schematem bazy gdzie uzytkownik jest polaczony z koszykiem przez order. Teraz tworzone przez te endpointy koszyki sa oderwane od usera?

Przegadajcie sobie to w zespole.

2021-09-26 16:36 UTC, leszczu89 commented
Uwzględniłam Usera w trakcie tworzenia koszyka. Nie wiem czy dobrze stworzyłam endpointy. Wydaje mi się że mało logiczne jest dodawanie produktów z poziomu koszyka. Ale takie są wytyczne.

2021-09-27 08:19 UTC, piotr-grosicki requested changes

2021-09-27 08:19 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public CartDto saveCart(@RequestBody UserDto userDto){
tutaj raczej nei potrzebny jest caly userDto, id powinno wystarczyc

2021-09-27 13:08 UTC, piotr-grosicki approved these changes

2021-09-27 13:08 UTC, merged